import React, { useRef, useState } from 'react';
import { Float, useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function RubixCube(props) {
  const { nodes, materials } = useGLTF('models/rubix-cube.glb');

    const cubeRef = useRef();
    const [hovered, setHovered] = useState(false);
    
    useFrame((state, delta) => {
      cubeRef.current.rotation.y += 0.01;
    });
  
  return (
    <Float floatIntensity={1}>
      <group rotation={[2.6, 0.8, -1.8]} dispose={null} {...props} ref={cubeRef}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_col2_0.geometry}
              material={materials.col2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_col5_0.geometry}
              material={materials.col5}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_col6_0.geometry}
              material={materials.col6}
            />
          </group>
          <group position={[202, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_col6_0.geometry}
              material={materials.col6}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_col2_0.geometry}
              material={materials.col2}
            />
          </group>
          <group position={[404, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube002_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube002_col6_0.geometry}
              material={materials.col6}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube002_col3_0.geometry}
              material={materials.col3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube002_col2_0.geometry}
              material={materials.col2}
            />
          </group>
          <group position={[0, 0, -202]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube003_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube003_col6_0.geometry}
              material={materials.col6}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube003_col5_0.geometry}
              material={materials.col5}
            />
          </group>
          <group position={[202, 0, -202]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube004_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube004_col6_0.geometry}
              material={materials.col6}
            />
          </group>
          <group position={[404, 0, -202]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube005_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube005_col6_0.geometry}
              material={materials.col6}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube005_col3_0.geometry}
              material={materials.col3}
            />
          </group>
          <group position={[0, 0, -404]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube006_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube006_col6_0.geometry}
              material={materials.col6}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube006_col5_0.geometry}
              material={materials.col5}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube006_col4_0.geometry}
              material={materials.col4}
            />
          </group>
          <group position={[202, 0, -404]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube007_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube007_col6_0.geometry}
              material={materials.col6}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube007_col4_0.geometry}
              material={materials.col4}
            />
          </group>
          <group position={[404, 0, -404]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube008_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube008_col6_0.geometry}
              material={materials.col6}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube008_col3_0.geometry}
              material={materials.col3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube008_col4_0.geometry}
              material={materials.col4}
            />
          </group>
          <group position={[0, 202, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube009_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube009_col5_0.geometry}
              material={materials.col5}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube009_col2_0.geometry}
              material={materials.col2}
            />
          </group>
          <group position={[202, 202, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube010_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube010_col2_0.geometry}
              material={materials.col2}
            />
          </group>
          <group position={[404, 202, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube011_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube011_col3_0.geometry}
              material={materials.col3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube011_col2_0.geometry}
              material={materials.col2}
            />
          </group>
          <group position={[0, 202, -202]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube012_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube012_col5_0.geometry}
              material={materials.col5}
            />
          </group>
          <group position={[404, 202, -202]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube014_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube014_col3_0.geometry}
              material={materials.col3}
            />
          </group>
          <group position={[0, 202, -404]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube015_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube015_col5_0.geometry}
              material={materials.col5}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube015_col4_0.geometry}
              material={materials.col4}
            />
          </group>
          <group position={[202, 202, -404]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube016_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube016_col4_0.geometry}
              material={materials.col4}
            />
          </group>
          <group position={[404, 202, -404]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube017_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube017_col3_0.geometry}
              material={materials.col3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube017_col4_0.geometry}
              material={materials.col4}
            />
          </group>
          <group position={[0, 404, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube018_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube018_col5_0.geometry}
              material={materials.col5}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube018_col1_0.geometry}
              material={materials.col1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube018_col2_0.geometry}
              material={materials.col2}
            />
          </group>
          <group position={[202, 404, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube019_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube019_col1_0.geometry}
              material={materials.col1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube019_col2_0.geometry}
              material={materials.col2}
            />
          </group>
          <group position={[404, 404, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube020_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube020_col3_0.geometry}
              material={materials.col3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube020_col1_0.geometry}
              material={materials.col1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube020_col2_0.geometry}
              material={materials.col2}
            />
          </group>
          <group position={[0, 404, -202]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube021_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube021_col5_0.geometry}
              material={materials.col5}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube021_col1_0.geometry}
              material={materials.col1}
            />
          </group>
          <group position={[202, 404, -202]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube022_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube022_col1_0.geometry}
              material={materials.col1}
            />
          </group>
          <group position={[404, 404, -202]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube023_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube023_col3_0.geometry}
              material={materials.col3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube023_col1_0.geometry}
              material={materials.col1}
            />
          </group>
          <group position={[0, 404, -404]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube024_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube024_col5_0.geometry}
              material={materials.col5}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube024_col4_0.geometry}
              material={materials.col4}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube024_col1_0.geometry}
              material={materials.col1}
            />
          </group>
          <group position={[202, 404, -404]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube025_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube025_col4_0.geometry}
              material={materials.col4}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube025_col1_0.geometry}
              material={materials.col1}
            />
          </group>
          <group position={[404, 404, -404]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube026_white_0.geometry}
              material={materials.white}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube026_col3_0.geometry}
              material={materials.col3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube026_col4_0.geometry}
              material={materials.col4}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube026_col1_0.geometry}
              material={materials.col1}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_white_0.geometry}
            material={materials.white}
            position={[202, 202, -202]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
      </group>
    </ Float>
  )
}

useGLTF.preload('models/rubix-cube.glb')
